//PRODUCTS 
export const PRODUCT_REQUEST="PRODUCT_REQUEST";
export const PRODUCT_RESPONSE="PRODUCT_RESPONSE";
export const LOADING='LOADING';

//SINGLE PRODUCT
export const PREQUEST_SINGLLE_PRODUCT="PREQUEST_SINGLLE_PRODUCT";
export const GET_SINGLLE_PRODUCT="GET_SINGLLE_PRODUCT";

//CART
export const ADD_ITEM_TO_CART="ADD_ITEM_TO_CART";
export const EDIT_ITEM_IN_CART="EDIT_ITEM_IN_CART";
export const UPDATE_ITEM_IN_CART='UPDATE_ITEM_IN_CART';
export const DELETE_ITEM_IN_CART='DELETE_ITEM_IN_CART';

export const GET_ITEMS_FROM_CART="GET_ITEMS_FROM_CART"
