//PRODUCTS 
export const PRODUCT_REQUEST="PRODUCT_REQUEST";
export const PRODUCT_RESPONSE="PRODUCT_RESPONSE";
export const LOADING='LOADING';

//SINGLE PRODUCT
export const PREQUEST_SINGLLE_PRODUCT="PREQUEST_SINGLLE_PRODUCT";
export const GET_SINGLLE_PRODUCT="GET_SINGLLE_PRODUCT";

//CART
export const ADD_ITEM_TO_CART="ADD_ITEM_TO_CART";
export const DELETE_ITEM_IN_CART='DELETE_ITEM_IN_CART';

export const INCREMENT_QUANTITY="INCREMENT_QUANTITY";
export const DECREMENT_QUANTITY='DECREMENT_QUANTITY';
export const INITALIZE_QUANTITY="INITALIZE_QUANTITY"